// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {time} from '../models';

export function CreateTask(arg1:string,arg2:string):Promise<domain.Task>;

export function CreateTaskWithDetails(arg1:string,arg2:string,arg3:string,arg4:time.Time):Promise<domain.Task>;

export function DeleteTask(arg1:string):Promise<void>;

export function GetAllTasks():Promise<Array<domain.Task>>;

export function GetFilteredTasks(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<Array<domain.Task>>;

export function GetTask(arg1:string):Promise<domain.Task>;

export function SetTaskDueDate(arg1:string,arg2:time.Time):Promise<domain.Task>;

export function SetTaskPriority(arg1:string,arg2:string):Promise<domain.Task>;

export function ToggleTaskStatus(arg1:string):Promise<domain.Task>;

export function UpdateTask(arg1:string,arg2:string,arg3:string):Promise<domain.Task>;
