// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTask(arg1, arg2) {
  return window['go']['main']['App']['CreateTask'](arg1, arg2);
}

export function CreateTaskWithDetails(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateTaskWithDetails'](arg1, arg2, arg3, arg4);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function GetAllTasks() {
  return window['go']['main']['App']['GetAllTasks']();
}

export function GetFilteredTasks(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetFilteredTasks'](arg1, arg2, arg3, arg4, arg5);
}

export function GetTask(arg1) {
  return window['go']['main']['App']['GetTask'](arg1);
}

export function SetTaskDueDate(arg1, arg2) {
  return window['go']['main']['App']['SetTaskDueDate'](arg1, arg2);
}

export function SetTaskPriority(arg1, arg2) {
  return window['go']['main']['App']['SetTaskPriority'](arg1, arg2);
}

export function ToggleTaskStatus(arg1) {
  return window['go']['main']['App']['ToggleTaskStatus'](arg1);
}

export function UpdateTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateTask'](arg1, arg2, arg3);
}
